version: 2.1
orbs:
  cypress: cypress-io/cypress@1.0.0
workflows:
  build:
    jobs:
    - cypress/install:
    pre-steps:
            - run: 'npm install chance --save-dev'
      - cypress/run:
          executor: cypress/base-8